version = 1

test_patterns = [
    "*/tests/**",
    "**/__tests__/**",
    "**/*.e2e.*"
]

exclude_patterns = [
    "demo/**",
    "docs/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

